import PageMeta from "@/components/common/PageMeta";
import AIReportCard from "./components/AIReportCard";
import AppointmentReasonsDistribution from "./components/AppointmentReasonsDistribution";
import AppointmentReasonsTrend from "./components/AppointmentReasonsTrend";

import { Sparkles} from "lucide-react";
import Badge from "@/components/badge/Badge";

const DashboardReports = () => {

  // const medicalInsights = useMemo(() => getMockMedicalRecordsInsights(), []);
  // const recommendations = useMemo(() => getMockRecommendations(), []);

  // Separate recommendations by priority
  // const highPriorityRecs = recommendations.filter((r) => r.priority === "high");
  // const mediumPriorityRecs = recommendations.filter(
  //   (r) => r.priority === "medium",
  // );
  // const lowPriorityRecs = recommendations.filter((r) => r.priority === "low");

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-950">
      <PageMeta
        title="CMS | AI Dashboard Reports"
        description="AI-Generated Clinic Analytics and Insights"
      />
      <div className="mb-6">
        <div className="flex items-center gap-3 mb-2">
          <Sparkles className="w-6 h-6 text-purple-600" />
          <h2 className="text-2xl font-bold text-gray-900 dark:text-white">
            AI-Generated Clinic Insights
          </h2>
          <Badge
            color="primary"
            variant="solid"
            startIcon={<Sparkles className="w-3 h-3" />}
          >
            Powered by AI
          </Badge>
        </div>
        <p className="text-sm text-gray-600 dark:text-gray-400">
          Advanced analytics and actionable recommendations generated from your
          clinic data to optimize operations and improve patient care.
        </p>
      </div>

      {/* AI Summary Report */}
      <div className="mb-6">
        <AIReportCard />
      </div>

      <div className="mb-6">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <AppointmentReasonsDistribution />
          <AppointmentReasonsTrend />
        </div>
      </div>

      {/* <div className="mb-6">
        <MedicalRecordsInsights insights={medicalInsights} />
      </div>

      <div>
        <div className="flex items-center gap-2 mb-4">
          <Sparkles className="w-5 h-5 text-purple-600" />
          <h3 className="text-lg font-semibold text-gray-900 dark:text-white">
            AI Recommendations
          </h3>
        </div>

        {highPriorityRecs.length > 0 && (
          <div className="mb-6">
            <h4 className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-3 flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-error-500"></span>
              High Priority Actions
            </h4>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {highPriorityRecs.map((rec) => (
                <RecommendationCard key={rec.id} recommendation={rec} />
              ))}
            </div>
          </div>
        )}

        {mediumPriorityRecs.length > 0 && (
          <div className="mb-6">
            <h4 className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-3 flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-warning-500"></span>
              Medium Priority Recommendations
            </h4>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {mediumPriorityRecs.map((rec) => (
                <RecommendationCard key={rec.id} recommendation={rec} />
              ))}
            </div>
          </div>
        )}

        {lowPriorityRecs.length > 0 && (
          <div>
            <h4 className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-3 flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-blue-500"></span>
              Low Priority Suggestions
            </h4>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {lowPriorityRecs.map((rec) => (
                <RecommendationCard key={rec.id} recommendation={rec} />
              ))}
            </div>
          </div>
        )}
      </div> */}

      <div className="mt-8 p-4 bg-purple-50 dark:bg-purple-950/20 rounded-lg border border-purple-200 dark:border-purple-900">
        <p className="text-xs text-purple-700 dark:text-purple-300 text-center">
          <strong>Note:</strong> These insights are generated by AI based on
          historical clinic data and statistical analysis. While highly
          accurate, recommendations should be reviewed by healthcare
          professionals before implementation.
        </p>
      </div>
    </div>
  );
};

export default DashboardReports;
