import type { Student, Teacher, Staff, Person, HealthItem } from "@/types/checkup"

export const mockStudents: Student[] = [
  {
    id: "STU-2024-001",
    name: "Maria Santos",
    grade: "Grade 7",
    section: "Section A",
    age: 13,
    type: "student",
    reasonForVisit: "Headache",
  },
  {
    id: "STU-2024-002",
    name: "Juan Dela Cruz",
    grade: "Grade 10",
    section: "Section B",
    age: 16,
    type: "student",
    reasonForVisit: "Fever",
  },
  {
    id: "STU-2024-003",
    name: "Angela Reyes",
    grade: "Grade 12",
    section: "STEM-A",
    age: 18,
    type: "student",
    reasonForVisit: "Stomachache",
  },
]

export const mockTeachers: Teacher[] = [
  {
    id: "TCH-2024-001",
    name: "Dr. Roberto Garcia",
    department: "Science Department",
    position: "Senior Teacher",
    age: 45,
    type: "teacher",
    reasonForVisit: "Dizziness",
  },
  {
    id: "TCH-2024-002",
    name: "Ms. Carmen Flores",
    department: "English Department",
    position: "Head Teacher",
    age: 38,
    type: "teacher",
    reasonForVisit: "Back Pain",
  },
  {
    id: "TCH-2024-003",
    name: "Mr. Antonio Ramos",
    department: "Math Department",
    position: "Teacher II",
    age: 32,
    type: "teacher",
    reasonForVisit: "Fatigue",
  },
]

export const mockStaff: Staff[] = [
  {
    id: "STF-2024-001",
    name: "Elena Mercado",
    department: "Administrative Office",
    role: "School Registrar",
    age: 42,
    type: "staff",
    reasonForVisit: "Allergic Reaction",
  },
  {
    id: "STF-2024-002",
    name: "Ricardo Villanueva",
    department: "Maintenance",
    role: "Head Custodian",
    age: 50,
    type: "staff",
    reasonForVisit: "Injury",
  },
  {
    id: "STF-2024-003",
    name: "Patricia Gomez",
    department: "Library",
    role: "Librarian",
    age: 35,
    type: "staff",
    reasonForVisit: "Nausea",
  },
]

export const allPersons: Person[] = [...mockStudents, ...mockTeachers, ...mockStaff]

export const healthItems: HealthItem[] = [
  // Medicines
  {
    id: "MED-001",
    name: "Paracetamol 500mg",
    category: "medicine",
    unit: "tablet",
    stockQuantity: 200,
    description: "For fever and mild pain relief",
  },
  {
    id: "MED-002",
    name: "Ibuprofen 200mg",
    category: "medicine",
    unit: "tablet",
    stockQuantity: 150,
    description: "Anti-inflammatory and pain relief",
  },
  {
    id: "MED-003",
    name: "Mefenamic Acid 250mg",
    category: "medicine",
    unit: "capsule",
    stockQuantity: 100,
    description: "For moderate pain relief",
  },
  {
    id: "MED-004",
    name: "Loperamide 2mg",
    category: "medicine",
    unit: "capsule",
    stockQuantity: 80,
    description: "For diarrhea",
  },
  {
    id: "MED-005",
    name: "Cetirizine 10mg",
    category: "medicine",
    unit: "tablet",
    stockQuantity: 120,
    description: "For allergies",
  },
  {
    id: "MED-006",
    name: "Oral Rehydration Salts",
    category: "medicine",
    unit: "sachet",
    stockQuantity: 50,
    description: "For dehydration",
  },
  // First Aid
  {
    id: "FA-001",
    name: "Adhesive Bandage (Band-Aid)",
    category: "first_aid",
    unit: "piece",
    stockQuantity: 300,
    description: "For small cuts and wounds",
  },
  {
    id: "FA-002",
    name: "Gauze Pad 4x4",
    category: "first_aid",
    unit: "piece",
    stockQuantity: 100,
    description: "For wound dressing",
  },
  {
    id: "FA-003",
    name: "Medical Tape",
    category: "first_aid",
    unit: "roll",
    stockQuantity: 25,
    description: "For securing bandages",
  },
  {
    id: "FA-004",
    name: "Elastic Bandage",
    category: "first_aid",
    unit: "roll",
    stockQuantity: 20,
    description: "For sprains and strains",
  },
  {
    id: "FA-005",
    name: "Cotton Balls",
    category: "first_aid",
    unit: "pack",
    stockQuantity: 30,
    description: "For cleaning wounds",
  },
  {
    id: "FA-006",
    name: "Antiseptic Solution (Betadine)",
    category: "first_aid",
    unit: "bottle",
    stockQuantity: 15,
    description: "For wound disinfection",
  },
  {
    id: "FA-007",
    name: "Alcohol 70%",
    category: "first_aid",
    unit: "bottle",
    stockQuantity: 20,
    description: "For disinfection",
  },
  // Supplies
  {
    id: "SUP-001",
    name: "Disposable Gloves",
    category: "supply",
    unit: "pair",
    stockQuantity: 200,
    description: "For hygiene and protection",
  },
  {
    id: "SUP-002",
    name: "Face Mask",
    category: "supply",
    unit: "piece",
    stockQuantity: 150,
    description: "For respiratory protection",
  },
  {
    id: "SUP-003",
    name: "Ice Pack",
    category: "supply",
    unit: "piece",
    stockQuantity: 10,
    description: "For cold compress",
  },
  {
    id: "SUP-004",
    name: "Hot Water Bag",
    category: "supply",
    unit: "piece",
    stockQuantity: 5,
    description: "For hot compress",
  },
  // Equipment
  {
    id: "EQP-001",
    name: "Digital Thermometer",
    category: "equipment",
    unit: "use",
    stockQuantity: 5,
    description: "For temperature measurement",
  },
  {
    id: "EQP-002",
    name: "Blood Pressure Monitor",
    category: "equipment",
    unit: "use",
    stockQuantity: 2,
    description: "For BP measurement",
  },
  {
    id: "EQP-003",
    name: "Pulse Oximeter",
    category: "equipment",
    unit: "use",
    stockQuantity: 3,
    description: "For oxygen saturation measurement",
  },
]

export const actionOptions: { value: string; label: string }[] = [
  { value: "rested", label: "Rested in Clinic" },
  { value: "medication_given", label: "Medication Given" },
  { value: "sent_home", label: "Sent Home" },
  { value: "first_aid", label: "First Aid Applied" },
  { value: "referred", label: "Referred to Hospital" },
]
