export enum UserRoles {
  SUPERUSER,
  STUDENTS,
  DOCTORS,
  CLINIC_STAFF,
  TEACHERS,
  PROCUREMENT,
  VISITOR,
}

export enum ExportOption {
  EXCEL,
  PDF,
}

export enum PaginatedType {
  PAGINATION,
  INFINITE,
}

export enum Courses {
  // EDUCATION
  BACHELOR_OF_SECONDARY_EDUCATION,
  BACHELOR_OF_ELEMENTARY_EDUCATION,

  // IT & ENGINEERING
  BACHELOR_OF_SCIENCE_IN_INFORMATION_TECHNOLOGY,
  BACHELOR_OF_SCIENCE_IN_COMPUTER_ENGINEERING,

  // BUSINESS & MANAGEMENT
  BACHELOR_OF_SCIENCE_IN_BUSINESS_ADMINISTRATION,
  BACHELOR_OF_SCIENCE_IN_OFFICE_ADMINISTRATION,

  // HOSPITALITY
  BACHELOR_OF_SCIENCE_IN_HOTEL_AND_RESTAURANT_MANAGEMENT,

  // CRIMINOLOGY
  BACHELOR_OF_SCIENCE_IN_CRIMINOLOGY,

  // LIBRARY SCIENCE
  BACHELOR_OF_LIBRARY_AND_INFORMATION_SCIENCE,
}

export enum YearLevels {
  FIRST_YEAR,
  SECOND_YEAR,
  THIRD_YEAR,
  FOURTH_YEAR,
}

export enum AppointmentReasons {
  FEVER_OR_FLU_LIKE_SYMPTOMS,
  HEADACHE_OR_MIGRAINE,
  STOMACHACHE_OR_DIGESTIVE_PROBLEMS,
  MINOR_INJURY_OR_ACCIDENT,
  ALLERGY_OR_ASTHMA_RELATED_SYMPTOMS,
  DENTAL_PAIN_OR_ORAL_HEALTH_CONCERNS,
  SKIN_CONDITIONS_OR_RASHES,
  // MEDICAL_CLEARANCE_OR_HEALTH_CERTIFICATION,
  FOLLOW_UP_CHECK_UP,
  OTHER_HEALTH_CONCERNS,
}

export enum AppointmentStatus {
  PENDING,
  APPROVED,
  RESCHEDULED,
  CANCELLED,
  COMPLETED,
  NO_SHOW,
  REASSIGN,
  CHECKUP_DONE,
}
export enum AppointmentType {
  SCHEDULED,
  WALK_IN,
  RESCHEDULED,
}

export enum DoctorSpecializations {
  GENERAL_DOCTOR,
}

export enum ApprovalStatus {
  PENDING,
  APPROVED,
  REJECTED,
  REASSIGN,
  RECEIVED,
}

export enum ActionTaken {
  RESTED,
  MEDICATION_GIVEN,
  SENT_HOME,
  FIRST_AID,
  REFERRED,
}

export enum UOM {
  PIECE,
  TABLET,
  CAPSULE,
  ML,
  LITER,
  BOTTLE,
  VIAL,
  AMPULE,
  ROLL,
  PACK,
  BOX,
  PAIR,
  UNIT,
  SET,
}

export enum FilterTimeIntervals {
  DAILY,
  WEEKLY,
  MONTHLY,
  YEARLY,
}

export enum Department {
  DEPT_IT,
  DEPT_BUSINESS,
  DEPT_EDUCATION,
  DEPT_HOSPITALITY,
  DEPT_OFFICE_ADMIN,
  DEPT_CRIMINOLOGY,
  DEPT_PSYCHOLOGY,
  DEPT_LIBRARY_SCIENCE,
}

export enum Position {
  INSTRUCTOR,
  ASSISTANT_PROFESSOR,
  ASSOCIATE_PROFESSOR,
  PROFESSOR,
  GUIDANCE_COUNSELOR,
  DEPARTMENT_HEAD,
}


export enum Gender {
  MALE,
  FEMALE
}
