export enum SYSTEMACCESS {
    DASHBOARD,


    USERS,

    STUDENT_DASHBOARD,
    APPOINTMENTS,
    OVERALL_APPOINTMENTS,

    DOCTOR_DASHBOARD,
    DOCTOR_APPOINTMENTS,

    ADD_VITAL_SIGN,
    ALL_TODAYS_APPOINTMENT,

    STAFF_DASHBOARD,

    ALL_PRODUCTS,
    MODIFY_PRODUCTS,

    PROCUREMENT_APPROVAL,
    MEDICAL_RECORDS,

    ALL_WALKINS,
    ALL_PATIENTS,

    STUDENT_MEDICAL_RECORDS,
    VIEW_MEDICAL_DATA,
    CREATE_MEDICAL_CERT,

    REQUEST_CERTIFICATES,
    EMERGENCY_CASE,
    ALL_HOSPITALS,
}