import { HospitalInfoDTO } from "@/types/emergencyCaseV2Types";
import { UOM } from "@/enums/commons";
import { GetProductPaginatedDTO } from "@/types/productTypes";

export const MOCK_PRODUCTS: GetProductPaginatedDTO[] = [
  new GetProductPaginatedDTO({
    Id: 1,
    Title: "Paracetamol 500mg",
    UOM: UOM.TABLET,
    Quantity: 500,
    PackagingQty: 100,
  }),
  new GetProductPaginatedDTO({
    Id: 2,
    Title: "Ibuprofen 400mg",
    UOM: UOM.TABLET,
    Quantity: 300,
    PackagingQty: 100,
  }),
  new GetProductPaginatedDTO({
    Id: 3,
    Title: "Amoxicillin 500mg",
    UOM: UOM.CAPSULE,
    Quantity: 200,
    PackagingQty: 50,
  }),
  new GetProductPaginatedDTO({
    Id: 4,
    Title: "Oral Rehydration Solution",
    UOM: UOM.SACHET,
    Quantity: 150,
    PackagingQty: 50,
  }),
  new GetProductPaginatedDTO({
    Id: 5,
    Title: "Betadine Solution 10%",
    UOM: UOM.ML,
    Quantity: 2000,
    PackagingQty: 10,
  }),
  new GetProductPaginatedDTO({
    Id: 6,
    Title: "Gauze Bandage 4x4",
    UOM: UOM.PIECE,
    Quantity: 400,
    PackagingQty: 100,
  }),
  new GetProductPaginatedDTO({
    Id: 7,
    Title: "Adhesive Bandage Strip",
    UOM: UOM.PIECE,
    Quantity: 600,
    PackagingQty: 100,
  }),
  new GetProductPaginatedDTO({
    Id: 8,
    Title: "Alcohol 70%",
    UOM: UOM.ML,
    Quantity: 5000,
    PackagingQty: 20,
  }),
  new GetProductPaginatedDTO({
    Id: 9,
    Title: "Cold Pack",
    UOM: UOM.PACK,
    Quantity: 50,
    PackagingQty: 10,
  }),
  new GetProductPaginatedDTO({
    Id: 10,
    Title: "Epinephrine 1mg/ml",
    UOM: UOM.AMPULE,
    Quantity: 30,
    PackagingQty: 10,
  }),
  new GetProductPaginatedDTO({
    Id: 11,
    Title: "Salbutamol Inhaler",
    UOM: UOM.INHALER,
    Quantity: 25,
    PackagingQty: 5,
  }),
  new GetProductPaginatedDTO({
    Id: 12,
    Title: "Cetirizine 10mg",
    UOM: UOM.TABLET,
    Quantity: 250,
    PackagingQty: 50,
  }),
  new GetProductPaginatedDTO({
    Id: 13,
    Title: "Hydrocortisone Cream",
    UOM: UOM.TUBE,
    Quantity: 40,
    PackagingQty: 10,
  }),
  new GetProductPaginatedDTO({
    Id: 14,
    Title: "Normal Saline 0.9%",
    UOM: UOM.ML,
    Quantity: 3000,
    PackagingQty: 10,
  }),
  new GetProductPaginatedDTO({
    Id: 15,
    Title: "Glucose Tablet",
    UOM: UOM.TABLET,
    Quantity: 100,
    PackagingQty: 20,
  }),
];

export const HOSPITALS_V2: HospitalInfoDTO[] = [
  {
    id: 1,
    name: "Metro General Hospital",
    address: "123 Rizal Ave, Quezon City, NCR",
    contactNumber: "+63-2-8888-0000",
    emergencyDepartment: "24/7 Emergency Room - Level 1 Trauma Center",
    ambulanceAvailable: true,
    specializations: ["Emergency Medicine", "Trauma Care", "General Surgery", "ICU"],
  },
  {
    id: 2,
    name: "St. Luke's Medical Center",
    address: "279 E. Rodriguez Sr. Blvd, Quezon City, NCR",
    contactNumber: "+63-2-8789-7700",
    emergencyDepartment: "Comprehensive Emergency Department",
    ambulanceAvailable: true,
    specializations: ["Cardiology", "Neurology", "Emergency Medicine", "Critical Care"],
  },
  {
    id: 3,
    name: "Philippine General Hospital",
    address: "Taft Ave, Ermita, Manila, NCR",
    contactNumber: "+63-2-5548-7000",
    emergencyDepartment: "Main Emergency Room",
    ambulanceAvailable: true,
    specializations: ["General Medicine", "Surgery", "Pediatrics", "Internal Medicine"],
  },
  {
    id: 4,
    name: "Cardinal Santos Medical Center",
    address: "Wilson St, San Juan, Metro Manila",
    contactNumber: "+63-2-8727-0001",
    emergencyDepartment: "Emergency and Critical Care Unit",
    ambulanceAvailable: true,
    specializations: ["Internal Medicine", "Critical Care", "Emergency", "Cardiology"],
  },
  {
    id: 5,
    name: "The Medical City",
    address: "Ortigas Ave, Pasig, Metro Manila",
    contactNumber: "+63-2-8988-1000",
    emergencyDepartment: "24-Hour Emergency Services",
    ambulanceAvailable: true,
    specializations: ["Multi-specialty", "Trauma", "Critical Care", "Pediatric Emergency"],
  },
];

export const MEDICAL_STAFF = [
  { id: 1, name: "Dr. Maria Santos", role: "School Physician", specialization: "General Medicine" },
  { id: 2, name: "Nurse Ana Reyes", role: "Head Nurse", specialization: "Emergency Nursing" },
  { id: 3, name: "Dr. Jose Lim", role: "Medical Consultant", specialization: "Internal Medicine" },
  { id: 4, name: "Nurse Ben Cruz", role: "First Aid Officer", specialization: "First Aid & CPR" },
  { id: 5, name: "Nurse Clara Torres", role: "Emergency Response Nurse", specialization: "Trauma Care" },
];

export const MEDICATIONS = [
  { id: 1, name: "Paracetamol 500mg", category: "Analgesic", unit: "tablet" },
  { id: 2, name: "Ibuprofen 400mg", category: "Anti-inflammatory", unit: "tablet" },
  { id: 3, name: "Amoxicillin 500mg", category: "Antibiotic", unit: "capsule" },
  { id: 4, name: "Oral Rehydration Solution", category: "Electrolyte", unit: "sachet" },
  { id: 5, name: "Betadine Solution 10%", category: "Antiseptic", unit: "ml" },
  { id: 6, name: "Gauze Bandage 4x4", category: "Wound Dressing", unit: "piece" },
  { id: 7, name: "Adhesive Bandage Strip", category: "Wound Care", unit: "piece" },
  { id: 8, name: "Alcohol 70%", category: "Antiseptic", unit: "ml" },
  { id: 9, name: "Cold Pack", category: "Cold Therapy", unit: "pack" },
  { id: 10, name: "Epinephrine 1mg/ml", category: "Emergency Drug", unit: "ampule" },
  { id: 11, name: "Salbutamol Inhaler", category: "Bronchodilator", unit: "puff" },
  { id: 12, name: "Cetirizine 10mg", category: "Antihistamine", unit: "tablet" },
  { id: 13, name: "Hydrocortisone Cream", category: "Anti-inflammatory", unit: "tube" },
  { id: 14, name: "Normal Saline 0.9%", category: "IV Solution", unit: "ml" },
  { id: 15, name: "Glucose Tablet", category: "Emergency", unit: "tablet" },
];

export const COMMON_SYMPTOMS = [
  "Fever",
  "Headache",
  "Dizziness",
  "Nausea",
  "Vomiting",
  "Abdominal Pain",
  "Chest Pain",
  "Shortness of Breath",
  "Cough",
  "Sore Throat",
  "Body Aches",
  "Fatigue",
  "Loss of Consciousness",
  "Seizure",
  "Bleeding",
  "Swelling",
  "Rash",
  "Difficulty Breathing",
];

export const MEDICATION_ROUTES = [
  "Oral",
  "Topical",
  "Intramuscular",
  "Intravenous",
  "Subcutaneous",
  "Inhalation",
  "Rectal",
];
